CREATE DATABASE company;
USE company;

CREATE TABLE EMPLOYEE (
    SSN VARCHAR(100),
    Name VARCHAR(100),
    Address VARCHAR(100),
    Sex CHAR(1),
    Salary DECIMAL(10, 2),
    SuperSSN VARCHAR(100),
    DNo INT,
    PRIMARY KEY (SSN)
);

CREATE TABLE DEPARTMENT (
    DNo INT,
    DName VARCHAR(100),
    MgrSSN VARCHAR(100),
    MgrStartDate DATE,
    PRIMARY KEY (DNo),
    FOREIGN KEY (MgrSSN) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE DLOCATION (
    DNo INT,
    DLoc VARCHAR(100),
    PRIMARY KEY (DNo, DLoc),
    FOREIGN KEY (DNo) REFERENCES DEPARTMENT(DNo)
);

CREATE TABLE PROJECT (
    PNo INT,
    PName VARCHAR(100),
    PLocation VARCHAR(100),
    DNo INT,
    PRIMARY KEY (PNo),
    FOREIGN KEY (DNo) REFERENCES DEPARTMENT(DNo)
);

CREATE TABLE WORKS_ON (
    SSN VARCHAR(100),
    PNo INT,
    Hours DECIMAL(5, 2),
    PRIMARY KEY (SSN, PNo),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (PNo) REFERENCES PROJECT(PNo)
);

-- Insert
INSERT INTO EMPLOYEE (SSN, Name, Address, Sex, Salary, SuperSSN, DNo)
VALUES ('1', 'John Doe', '123 Main St', 'M', 50000, '2', 1);

-- Update
UPDATE EMPLOYEE
SET Address = '456 Elm St'
WHERE SSN = '1';

-- Delete
DELETE FROM EMPLOYEE
WHERE SSN = '1';

SELECT Name
FROM EMPLOYEE
ORDER BY Name ASC;

SELECT *
FROM EMPLOYEE
WHERE Name = 'AMIT' AND Salary > 50000;
