CREATE DATABASE college;
USE college;

CREATE TABLE STUDENT (
    USN VARCHAR(100),
    SName VARCHAR(100),
    Address VARCHAR(100),
    Phone VARCHAR(15),
    Gender CHAR(1),
    PRIMARY KEY (USN)
);

CREATE TABLE SEMSEC (
    SSID VARCHAR(100),
    Sem INT,
    Sec CHAR(1),
    PRIMARY KEY (SSID)
);

CREATE TABLE CLASS (
    USN VARCHAR(100),
    SSID VARCHAR(100),
    PRIMARY KEY (USN, SSID),
    FOREIGN KEY (USN) REFERENCES STUDENT(USN),
    FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID)
);

CREATE TABLE SUBJECT (
    Subcode VARCHAR(100),
    Title VARCHAR(100),
    Sem INT,
    Credits INT,
    PRIMARY KEY (Subcode)
);

CREATE TABLE IAMARKS (
    USN VARCHAR(100),
    Subcode VARCHAR(100),
    SSID VARCHAR(100),
    Test1 DECIMAL(5, 2),
    Test2 DECIMAL(5, 2),
    Test3 DECIMAL(5, 2),
    FinalIA DECIMAL(5, 2),
    PRIMARY KEY (USN, Subcode, SSID),
    FOREIGN KEY (USN) REFERENCES STUDENT(USN),
    FOREIGN KEY (Subcode) REFERENCES SUBJECT(Subcode),
    FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID)
);

ALTER TABLE dept CHANGE DNAME DEPT_NAME datatype(length);
DROP TABLE tablename;
DELETE FROM tablename;
